"""Phase 0 helper: generate a synthetic multi-page PDF with KNOWN content.

Using controlled text (instead of a random downloaded paper) lets the spike
verify offset round-tripping deterministically: we know exactly which sentence
the answer must cite and can assert it relocates in the parsed markdown.
"""

from fpdf import FPDF

# The "needle" — a precise, citable factual claim the grounded answer must use.
NEEDLE = (
    "Across six independent samples, learners with higher post-training spindle "
    "density over parietal sites recalled significantly more word-pair associations "
    "at next-day test (mean r = 0.51, p < .001)."
)

PAGES = [
    {
        "heading": "1. Introduction",
        "body": [
            "Sleep plays an active role in the consolidation of newly acquired "
            "declarative memories. Non-rapid-eye-movement (NREM) sleep, and stage 2 "
            "in particular, is characterized by sleep spindles: brief 11-16 Hz "
            "oscillations generated by the thalamic reticular nucleus.",
            "This report reviews the relationship between spindle activity and "
            "overnight retention of verbal material, and the role of targeted memory "
            "reactivation (TMR) in biasing which memories are rehearsed during sleep.",
        ],
    },
    {
        "heading": "2. Spindles and declarative recall",
        "body": [
            "A growing body of evidence links NREM sleep architecture to the "
            "strengthening of hippocampally-mediated declarative memories. Sleep "
            "spindles have emerged as a reliable electrophysiological marker of "
            "overnight consolidation.",
            NEEDLE,
            "The magnitude of this relationship was largest for items that "
            "participants had rated as difficult at study, consistent with a "
            "preferential stabilization of weaker memory traces.",
        ],
    },
    {
        "heading": "3. Targeted memory reactivation",
        "body": [
            "By replaying a cue paired with learning material during subsequent NREM "
            "sleep, researchers can bias which memories the sleeping brain rehearses. "
            "The pooled benefit for cued versus uncued items was 11.2 percent in "
            "recall accuracy across 47 experiments.",
            "When the cue was instead paired with an extinction trial, the same "
            "protocol produced a small but reliable weakening of the targeted memory, "
            "demonstrating that TMR is bidirectional and content-specific.",
        ],
    },
]


def build(path: str = "test_doc.pdf") -> str:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    for page in PAGES:
        pdf.add_page()
        pdf.set_font("Helvetica", style="B", size=15)
        pdf.multi_cell(0, 9, page["heading"])
        pdf.ln(3)
        pdf.set_font("Helvetica", size=12)
        for para in page["body"]:
            pdf.multi_cell(0, 7, para)
            pdf.ln(3)
    pdf.output(path)
    return path


if __name__ == "__main__":
    out = build()
    print(f"Wrote {out}")
    print(f"NEEDLE sentence:\n  {NEEDLE}")
